const state = { view: location.hash.slice(1) || "today", recommendation: "active", selectedAssumption: null, intakePreview: false, intakeDraft: null, assumptionFilter: "all", completionTaskId: null, showTaskForm: false, showExperimentForm: false, showAssumptionForm: false, experimentMenuId: null, completingExperimentId: null, linkingEvidenceId: null, loading: true, projectId: null, project: null, assumptions: [], evidence: [], experiments: [], tasks: [], decisions: [], events: [] };
const toTitle = value => String(value || "").split("_").map(part => part[0] ? part[0].toUpperCase() + part.slice(1) : "").join(" ");
const experimentColumn = status => ({ running: "Active", proposed: "Proposed", completed: "Completed", paused: "Proposed", failed: "Completed" })[status] || toTitle(status);
const dateLabel = value => value ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(value)) : "No due date";
async function request(url, options = {}) { const response = await fetch(url, { headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(body.error || "Request failed"); return body; }
function hydrate(memory) { const p = memory.project; state.projectId = p.id; state.project = { name: p.name, shortDescription: p.short_description || "", targetCustomer: p.target_customer || "", targetBuyer: "", problem: p.problem_statement || "", solution: p.solution_summary || "", pricing: p.pricing_hypothesis || "", revenueModel: p.revenue_model || "", salesMotion: "", validation: p.validation_stage || p.stage || "idea" }; const links = memory.assumption_evidence || []; state.assumptions = memory.assumptions.map(a => ({ id:a.id, statement:a.statement, category:a.category, status:a.status, priority:toTitle(a.priority), confidence:toTitle(a.confidence), risk:a.risk_score, blocker:a.revenue_blocker, evidence:links.filter(l => l.assumption_id === a.id).length, why:a.subcategory || "This belief needs direct evidence before it can guide the company." })); state.evidence = memory.evidence.map(e => ({ id:e.id, source:toTitle(e.source_type), person:e.source_person_name || e.source_title, date:dateLabel(e.source_date || e.created_at), summary:e.summary, strength:toTitle(e.strength), signal:toTitle(e.behavior_vs_opinion), links:links.filter(l => l.evidence_id === e.id).map(l => ({ id:l.assumption_id, relationship:toTitle(l.relationship) })) })); state.experiments = memory.experiments.map(e => ({ id:e.id, title:e.title, kind:experimentColumn(e.status), assumption:e.assumption_id, hypothesis:e.hypothesis, method:e.test_design || "", metric:e.success_metric, due:e.expected_duration || "No due date", status:toTitle(e.status), result:e.status === "completed" ? (e.test_design || "Result recorded.") : "" })); state.tasks = memory.tasks.map(t => ({ id:t.id, title:t.title, description:t.description || "", status:t.status, priority:toTitle(t.priority), impact:toTitle(t.impact_level || "medium"), firstRevenue:t.impact_level === "first_revenue", minutes:t.estimated_minutes || 20, assumption:t.assumption_id, experiment:t.experiment_id, today:t.status !== "done" })); state.decisions = memory.decisions; state.events = memory.events.map(event => event.summary); state.selectedAssumption ||= state.assumptions[0]?.id || null; state.loading = false; }
async function loadMemory(projectId = state.projectId) { state.loading = true; render(); try { const memory = await request(`/api/projects/${projectId}/memory`); hydrate(memory); } catch (error) { state.loading = false; toast(error.message); } render(); }
async function mutate(path, method, body) { try { await request(path, { method, body: body ? JSON.stringify(body) : undefined }); await loadMemory(); } catch (error) { toast(error.message); } }
function draftProject(payload) { return { name: payload.name || "New project", shortDescription: payload.short_description || "", targetCustomer: payload.target_customer || "", targetBuyer: "", problem: payload.problem_statement || "", solution: payload.solution_summary || "", pricing: payload.pricing_hypothesis || "", revenueModel: "Subscription", salesMotion: "", validation: payload.validation_stage || payload.stage || "idea" }; }

const $ = (s) => document.querySelector(s);
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"})[c]);
const label = (id) => state.assumptions.find(a => a.id === id)?.statement || "—";
const badge = (value, kind = "") => `<span class="badge ${kind || value.toLowerCase().replaceAll(" ", "-")}">${esc(value)}</span>`;
const titleCase = (s) => s[0].toUpperCase() + s.slice(1);

function layout(title, eyebrow, content, action = "") { return `<section class="page"><header class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div>${action}</header>${content}</section>`; }
function progress() { const done = state.tasks.filter(t=>t.status === "done").length; return `<div class="revenue-progress"><div><span>Path to first dollar</span><strong>${done} of 5 validation moves complete</strong></div><div class="progress-track"><i style="width:${done / 5 * 100}%"></i></div><small>Current focus: secure a paid pilot</small></div>`; }
function nextAction(){return [...state.tasks].filter(t=>t.status!=="done").sort((a,b)=>Number(b.firstRevenue)-Number(a.firstRevenue)||({High:3,Medium:2,Low:1}[b.priority]-({High:3,Medium:2,Low:1}[a.priority])))[0];}
function dueTone(due, completed){const day=Number(String(due).match(/\d+/)?.[0]);if(completed||!day||day<3)return "past";return day-3<=2?"urgent":day-3<=7?"soon":"upcoming";}
function taskRow(t, compact=false) { const validation=state.completionTaskId===t.id?`<form class="completion-form" id="completionForm" data-id="${t.id}"><label>What proves this task is complete?<input name="proof" placeholder="e.g. Invitation sent and reply tracked" required></label><button class="button primary" type="submit">Confirm completion</button><button type="button" class="text-button" data-action="cancel-completion">Cancel</button></form>`:""; return `<article class="task-row ${t.status === "done" ? "is-done" : ""}"><button class="check ${t.status === "done" ? "checked" : ""}" data-action="toggle-task" data-id="${t.id}" aria-label="Mark task ${t.status === "done" ? "incomplete" : "complete"}">${t.status === "done" ? "✓" : ""}</button><div class="task-main"><div class="task-title">${esc(t.title)}${t.firstRevenue?` ${badge("First revenue","first-revenue")}`:""}</div>${compact ? "" : `<p>${esc(t.description)}</p>`}<div class="task-meta">${badge(titleCase(t.priority))} <span>${esc(t.impact)} impact</span><span>${t.minutes} min</span></div>${validation}</div>${!compact ? `<span class="task-state">${titleCase(t.status)}</span>` : ""}</article>`; }
function assumptionCard(a, featured=false) { return `<article class="assumption-card ${featured ? "featured" : ""} ${state.selectedAssumption === a.id ? "selected" : ""}" data-action="select-assumption" data-id="${a.id}"><div class="assumption-top"><span class="category">${esc(a.category)}</span>${badge(a.status)}</div><h3>${esc(a.statement)}</h3><div class="assumption-stats"><span><b>${a.risk}</b> risk score</span><span>${a.evidence} evidence ${a.evidence === 1 ? "link" : "links"}</span>${a.blocker ? `<span class="blocker">◆ Revenue blocker</span>` : ""}</div><div class="confidence"><i style="width:${a.risk}%"></i></div><p class="why"><strong>Why this matters:</strong> <span contenteditable="true" data-action="edit-assumption-why" data-id="${a.id}">${esc(a.why)}</span></p>${a.status==="untested"?`<button class="text-button test-button" data-action="mark-testing" data-id="${a.id}">Mark as being tested</button>`:""}</article>`; }

function today() {
 const rec = state.recommendation;
 const task = nextAction() || { title:"Create your first validation task", description:"Turn the next customer-learning step into a concrete task.", assumption:null, minutes:15 }; const exp = state.experiments.find(e=>e.status==="Running") || state.experiments[0] || { title:"No active experiment", status:"Proposed", hypothesis:"Create an experiment tied to your riskiest assumption.", metric:"Define a behavior-based success metric", due:"—" }; const risky = state.assumptions.find(a=>a.id===state.selectedAssumption) || state.assumptions[0] || { risk:0, category:"No assumptions yet", statement:"Add the belief that most affects first revenue.", why:"Company memory is ready for your first assumption." };
 const recBlock = rec === "active" ? `<article class="next-action"><div class="action-label"><span class="spark">✦</span> YOUR NEXT BEST ACTION</div><h2>${esc(task.title)}</h2><p>${esc(task.description)}</p><div class="action-details"><div><span>Tests</span><strong>${esc(label(task.assumption))}</strong></div><div><span>Expected impact</span><strong>Unlock first revenue</strong></div><div><span>Time</span><strong>${task.minutes} minutes</strong></div></div><div class="action-buttons"><button class="button primary" data-action="focus-task" data-id="${task.id}">Start task <span>→</span></button><button class="button ghost" data-action="snooze-rec">Snooze</button><button class="text-button" data-action="dismiss-rec">Dismiss</button></div></article>` : `<article class="next-action muted"><div class="action-label"><span class="spark">✦</span> RECOMMENDATION ${rec === "snoozed" ? "SNOOZED" : "DISMISSED"}</div><h2>${rec === "snoozed" ? "We'll bring this back tomorrow." : "Choose your next focus."}</h2><p>${rec === "snoozed" ? "Use this space to keep moving on your active experiment." : "Review your open tasks to select the most important next move."}</p><button class="button ghost" data-action="restore-rec">Restore recommendation</button></article>`;
 return layout("Good morning, Sarah.", "Monday, August 3", `<div class="today-grid"><div class="main-column">${recBlock}<section class="section"><div class="section-heading"><div><p class="eyebrow">ACTIVE EXPERIMENT</p><h2>${esc(exp.title)}</h2></div>${badge(exp.status)}</div><div class="experiment-summary"><div><span>Hypothesis</span><p>${esc(exp.hypothesis)}</p></div><div><span>Success looks like</span><p>${esc(exp.metric)}</p></div><div><span>Due</span><p>${esc(exp.due)}</p></div></div><a class="inline-link" href="#experiments" data-view-link="experiments">View experiment details →</a></section><section class="section"><div class="section-heading"><div><p class="eyebrow">OPEN TASKS</p><h2>Keep the momentum</h2></div><a class="inline-link" href="#tasks" data-view-link="tasks">See all tasks →</a></div><div class="task-list">${state.tasks.filter(t=>t.status!=="done").slice(0,3).map(t=>taskRow(t,true)).join("")}</div></section><section class="section"><p class="eyebrow">RECENT ACTIVITY</p><div class="task-list">${state.events.slice(0,4).map(event=>`<div class="task-row"><span class="source-dot"></span><div class="task-main"><div class="task-title">${esc(event)}</div></div></div>`).join("")}</div></section></div><aside class="right-column"><section class="risk-panel"><p class="eyebrow">TOP RISK</p><h2>${risky.risk}<small>/100</small></h2><span class="risk-caption">${esc(risky.category)}</span><h3>${esc(risky.statement)}</h3><p>${esc(risky.why)}</p><a href="#assumptions" data-view-link="assumptions" class="inline-link">Explore assumptions →</a></section><section class="evidence-mini"><div class="section-heading"><div><p class="eyebrow">RECENT EVIDENCE</p><h2>What you learned</h2></div></div>${state.evidence.slice(0,2).map(e=>`<div class="mini-evidence"><span class="source-dot"></span><div><strong>${esc(e.person)}</strong><p>${esc(e.summary)}</p></div></div>`).join("")}<a href="#evidence" data-view-link="evidence" class="inline-link">View evidence inbox →</a></section>${progress()}</aside></div>`);
}

function memoryField(labelText, key, source) { return `<div class="memory-field"><span>${labelText}</span><div><strong contenteditable="true" data-action="edit-memory" data-key="${key}" spellcheck="false">${esc(state.project[key])}</strong>${badge(source, source === "user confirmed" ? "confirmed" : source === "user provided" ? "provided" : "inferred")}${source === "llm inferred" ? `<button class="confirm" data-action="confirm-field" data-key="${key}">Confirm</button>` : ""}</div></div>`; }
function memory() { return layout("Company memory", "THE STRUCTURED STORY OF YOUR COMPANY", `<div class="memory-intro"><p>These are the facts ${esc(state.project.name)} is operating from. Edit any field to write it to persistent company memory.</p><span class="legend">${badge("user provided", "provided")}${badge("llm inferred", "inferred")}${badge("user confirmed", "confirmed")}</span></div><div class="memory-grid"><section class="memory-card"><p class="eyebrow">CORE IDENTITY</p>${memoryField("Company", "name", "user confirmed")}${memoryField("Description", "shortDescription", "user provided")}${memoryField("Validation stage", "validation", "llm inferred")}</section><section class="memory-card"><p class="eyebrow">CUSTOMER & PROBLEM</p>${memoryField("Target customer", "targetCustomer", "user confirmed")}${memoryField("Initial buyer", "targetBuyer", "llm inferred")}${memoryField("Pain to solve", "problem", "user confirmed")}</section><section class="memory-card"><p class="eyebrow">SOLUTION & BUSINESS MODEL</p>${memoryField("Solution", "solution", "user provided")}${memoryField("Pricing hypothesis", "pricing", "user confirmed")}${memoryField("Revenue model", "revenueModel", "llm inferred")}${memoryField("Sales motion", "salesMotion", "llm inferred")}</section><section class="memory-card decisions-card"><p class="eyebrow">ACTIVE DECISIONS</p>${state.decisions.map(d=>`<article class="decision"><strong>${esc(d.title)}</strong><p>${esc(d.decision)}</p><small>${esc(d.reason || "")}</small></article>`).join("") || `<div class="empty-state">No decisions saved yet.</div>`}</section></div>`); }

function assumptions() { const all=[...state.assumptions].sort((a,b)=>b.risk-a.risk), list=all.filter(a=>state.assumptionFilter==="all"||state.assumptionFilter==="blockers"&&a.blocker||state.assumptionFilter==="untested"&&a.status==="untested"); return layout("Assumptions", "WHAT MUST BE TRUE FOR THIS COMPANY TO WORK", `<div class="assumption-hero"><div><p>Every early company is a stack of unproven beliefs. Test the most consequential ones first.</p><div class="filter-chips"><button class="chip ${state.assumptionFilter==="all"?"active":""}" data-action="filter-assumptions" data-filter="all">All (${all.length})</button><button class="chip ${state.assumptionFilter==="blockers"?"active":""}" data-action="filter-assumptions" data-filter="blockers">Revenue blockers</button><button class="chip ${state.assumptionFilter==="untested"?"active":""}" data-action="filter-assumptions" data-filter="untested">Untested</button><button class="chip" data-action="show-assumption-form">+ Add assumption</button></div></div><div class="risk-explainer"><span>Risk score</span><strong>${all[0]?.risk ?? "—"}${all.length ? "/100" : ""}</strong><p>Impact + uncertainty + revenue blocker − evidence</p></div></div>${state.showAssumptionForm?`<form class="evidence-form" id="assumptionForm"><label>Assumption<input name="statement" required placeholder="What must be true?"></label><div class="form-grid"><label>Category<select name="category"><option>Problem</option><option>Willingness to pay</option><option>Distribution</option><option>Solution</option></select></label><label>Priority<select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></label></div><label>Why it matters (editable later)<input name="why" required placeholder="How it affects this company"></label><button class="button primary">Save assumption</button></form>`:""}<div class="assumption-list">${list.map((a,i)=>assumptionCard(a,i===0)).join("") || `<div class="empty-state">No assumptions match this filter.</div>`}</div>`); }

function evidence() { return layout("Evidence inbox", "MARKET LEARNING, CONNECTED TO WHAT YOU BELIEVE", `<div class="evidence-layout"><div><div class="evidence-toolbar"><p>${state.evidence.length} pieces of market evidence</p><button class="button primary" data-action="show-evidence-form">+ Add evidence</button></div><form class="evidence-form hidden" id="evidenceForm"><div class="form-grid"><label>Source type<select name="source"><option>Manual note</option><option>Customer interview</option><option>Sales call</option></select></label><label>Who / source title<input name="person" placeholder="e.g. Jamie, 8th grade teacher" required></label><label>Signal type<select name="signal"><option>Opinion</option><option>Stated intent</option><option>Behavior</option><option>Payment</option></select></label><label>Strength<select name="strength"><option>Weak</option><option>Moderate</option><option>Strong</option></select></label></div><label>What did you learn?<textarea name="summary" placeholder="Paste an interview note or market observation…" required></textarea></label><div class="form-actions"><button class="button primary" type="submit">Save draft evidence</button><button class="button ghost" type="button" data-action="hide-evidence-form">Cancel</button></div></form><div class="evidence-list">${state.evidence.map(e=>evidenceCard(e)).join("")}</div></div><aside class="evidence-side"><p class="eyebrow">EVIDENCE QUALITY</p><h2>Strength is a founder-reviewed judgment.</h2><ol><li><b>Strong:</b> payment, commitment, or repeated behavior</li><li><b>Moderate:</b> specific pain or stated intent</li><li><b>Weak:</b> a single opinion or vague encouragement</li></ol><p>The source, recency, specificity, and whether the signal is behavior—not opinion—inform the initial suggestion. The founder can override it.</p></aside></div>`); }
function evidenceCard(e) { const linker=state.linkingEvidenceId===e.id?`<form class="link-form" id="linkForm" data-id="${e.id}"><select name="assumption">${state.assumptions.map(a=>`<option value="${a.id}">${esc(a.statement)}</option>`).join("")}</select><select name="relationship"><option>Supports</option><option>Contradicts</option><option>Neutral</option></select><button class="button primary">Link</button></form>`:""; return `<article class="evidence-card"><div class="evidence-head"><div><span class="source-icon">◌</span><span class="source-type">${esc(e.source)}</span><h3>${esc(e.person)}</h3></div><small>${esc(e.date)}</small></div><p>${esc(e.summary)}</p><div class="evidence-footer">${badge(e.strength)} ${badge(e.signal, "signal")}<div class="linked">${e.links.map(l=>`<button data-action="select-assumption" data-id="${l.id}"><span class="link-${l.relationship.toLowerCase()}">●</span>${esc(l.relationship)}: ${esc(label(l.id))}</button>`).join("")}</div><button class="text-button" data-action="link-evidence" data-id="${e.id}">+ Link assumption</button></div>${linker}</article>`; }

function experiments() { const groups = ["Active","Proposed","Completed"]; return layout("Experiments", "TEST BELIEFS WITH REAL CUSTOMER BEHAVIOR", `<div class="evidence-toolbar"><p class="page-intro">A good experiment produces a decision, not just more opinions.</p><button class="button primary" data-action="show-experiment-form">+ Propose experiment</button></div>${state.showExperimentForm?`<form class="evidence-form" id="experimentForm"><label>Experiment title<input name="title" required placeholder="What will you test?"></label><label>Hypothesis<textarea name="hypothesis" required></textarea></label><div class="form-grid"><label>Related assumption<select name="assumption">${state.assumptions.map(a=>`<option value="${a.id}">${esc(a.statement)}</option>`).join("")}</select></label><label>Due date<input name="due" value="Aug 12" required></label></div><label>Success metric<input name="metric" required placeholder="e.g. 2 paid pilots"></label><button class="button primary">Save proposed experiment</button></form>`:""}<div class="experiment-board">${groups.map(group=>`<section class="experiment-column"><header><h2>${group}</h2><span>${state.experiments.filter(e=>e.kind===group).length}</span></header>${state.experiments.filter(e=>e.kind===group).map(experimentCard).join("") || `<div class="empty-state">Nothing here yet.</div>`}</section>`).join("")}</div>`); }
function experimentCard(e) { const related = label(e.assumption), due=dueTone(e.due,e.kind==="Completed"), menu=state.experimentMenuId===e.id?`<div class="card-menu"><button data-action="record-result" data-id="${e.id}">Record result</button><button data-action="start-experiment" data-id="${e.id}">Start</button></div>`:"", resultForm=state.completingExperimentId===e.id?`<form class="completion-form" id="experimentResultForm" data-id="${e.id}"><label>Result and learning<textarea name="result" required placeholder="What happened? What changes next?"></textarea></label><label>Did the success metric pass?<select name="metricStatus"><option>Met</option><option>Partially met</option><option>Not met</option></select></label><button class="button primary">Complete experiment</button></form>`:""; return `<article class="experiment-card"><div class="experiment-card-top">${badge(e.status)}<button class="more-button" data-action="experiment-menu" data-id="${e.id}" aria-label="Experiment options">•••</button>${menu}</div><h3>${esc(e.title)}</h3><p>${esc(e.hypothesis)}</p><div class="experiment-detail"><span>Success metric ${e.metricStatus?`· ${esc(e.metricStatus)}`:""}</span><strong>${esc(e.metric)}</strong></div><div class="experiment-foot"><span class="due ${due}">Due ${esc(e.due)}</span><button class="assumption-link" data-action="select-assumption" data-id="${e.assumption}">${esc(related)}</button></div>${e.status === "Proposed" ? `<button class="button full" data-action="start-experiment" data-id="${e.id}">Start experiment</button>` : e.status === "Running" ? `<button class="button full" data-action="record-result" data-id="${e.id}">Record result & complete</button>` : ""}${resultForm}${e.result ? `<div class="result"><strong>Result · Metric ${esc(e.metricStatus)}</strong>${esc(e.result)}</div>` : ""}</article>`; }

function tasks() { const groups=[{name:"Today",filter:t=>t.today&&t.status!=="done"},{name:"Upcoming",filter:t=>!t.today&&t.status!=="done"},{name:"Done",filter:t=>t.status==="done"}], first=state.tasks.filter(t=>t.firstRevenue&&t.status!=="done"); return layout("Tasks", "CONCRETE WORK TIED TO FIRST REVENUE", `<div class="tasks-layout"><div><div class="task-summary"><span><b>${state.tasks.filter(t=>t.status!=="done").length}</b> open tasks</span><span><b>${first.length}</b> tied to first revenue</span><button class="button ghost" data-action="add-task">+ Add task</button></div>${state.showTaskForm?`<form class="evidence-form" id="taskForm"><label>Task title<input name="title" required placeholder="Describe the concrete action"></label><label>Description<input name="description" required placeholder="What does done look like?"></label><div class="form-grid"><label>Priority<select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></label><label><input type="checkbox" name="firstRevenue"> Directly tied to first revenue</label></div><button class="button primary">Create task</button></form>`:""}${groups.map(g=>`<section class="task-group"><h2>${g.name}<span>${state.tasks.filter(g.filter).length}</span></h2>${state.tasks.filter(g.filter).map(t=>taskRow(t)).join("") || `<div class="empty-state">Nothing here yet.</div>`}</section>`).join("")}</div>${first.length?`<aside class="task-aside"><p class="eyebrow">FOCUS FOR GRADEFLOW</p><h2>Secure a paid pilot.</h2><p>${first.length} open tasks are explicitly tied to the paid-pilot experiment and the pricing assumption.</p><div class="first-dollar-card"><span>◆</span><div><strong>Company-specific trigger</strong><p>Pricing is still untested with no payment evidence.</p></div></div></aside>`:""}</div>`); }

function intake() { const preview = state.intakePreview, project = state.project || state.intakeDraft || {}; return layout("Start with the messy version.", "IDEA INTAKE", `<div class="intake-layout"><form class="intake-form" id="intakeForm"><label class="large-label">What are you building, who is it for, and what progress have you made?<textarea name="idea" placeholder="I’m building an AI tool that helps teachers grade homework faster…">I’m building an AI tool that helps middle school teachers grade written homework faster. I’ve spoken with three teachers who say grading steals their weekends.</textarea></label><div class="form-grid"><label>Target customer <input name="customer" value="Middle school teachers"></label><label>Problem <input name="problem" value="Grading takes 5–8 hours a week"></label><label>Proposed solution <input name="solution" value="AI-assisted feedback workspace"></label><label>Pricing guess <input name="price" value="$15/month"></label><label>Current progress <input name="progress" value="3 customer interviews"></label><label>First-dollar goal <input name="goal" value="2 paid pilots"></label></div><button class="button primary" type="submit">Preview structured profile <span>→</span></button></form><aside class="intake-preview ${preview ? "visible" : ""}">${preview ? `<div class="preview-label"><span class="spark">✦</span> STATIC AI PREVIEW</div><h2>Here’s the company I see.</h2><p>This is a mock extraction. In Milestone 3, it will be generated from your input.</p><div class="preview-fields"><div><span>Target customer</span><strong>${esc(project.targetCustomer || "")}</strong><button data-action="confirm-field" data-key="targetCustomer">Confirm</button></div><div><span>Problem</span><strong>${esc(project.problem || "")}</strong><button data-action="confirm-field" data-key="problem">Confirm</button></div><div><span>Solution</span><strong>${esc(project.solution || "")}</strong><button data-action="confirm-field" data-key="solution">Confirm</button></div><div><span>Pricing hypothesis</span><strong>${esc(project.pricing || "")}</strong><button data-action="confirm-field" data-key="pricing">Confirm</button></div><div><span>Revenue model</span><strong>${esc(project.revenueModel || "Subscription")}</strong>${badge("llm inferred", "inferred")}</div></div>${state.projectId ? `<a class="button ghost full" href="#memory" data-view-link="memory">Review company memory</a>` : `<button class="button ghost full" type="button" disabled>Saving company memory...</button>`}</aside>` : `<div class="preview-empty"><span>✦</span><h2>Your structured company profile will appear here.</h2><p>We’ll keep important fields visible for review before they become working memory.</p></div>`}</aside></div>`); }

const views = {today, intake, memory, assumptions, evidence, experiments, tasks};
function emptyProject() { return layout("Start your company memory", "DATABASE-BACKED MEMORY", `<div class="empty-state">Create your first project to begin storing assumptions, evidence, experiments, and tasks in Postgres.<br><br><a class="button primary" href="#intake" data-view-link="intake">Create a project →</a></div>`); }
function attachCancelControls(){const controls={intakeForm:"cancel-intake",taskForm:"cancel-task-form",assumptionForm:"cancel-assumption-form",linkForm:"cancel-link-form",experimentForm:"cancel-experiment-form",experimentResultForm:"cancel-experiment-result"};Object.entries(controls).forEach(([id,action])=>{const form=document.getElementById(id);if(!form||form.querySelector(`[data-action="${action}"]`))return;const button=document.createElement("button");button.type="button";button.className="button ghost cancel-button";button.dataset.action=action;button.textContent="Cancel";form.append(button);});}
function render() { state.view = location.hash.slice(1) || state.view || "today"; if (!views[state.view]) state.view="today"; const app = $("#app"); app.innerHTML = state.loading ? `<section class="page"><div class="empty-state">Loading company memory…</div></section>` : (!state.project && state.view !== "intake" ? emptyProject() : views[state.view]()); document.querySelectorAll(".nav-link").forEach(l=>l.classList.toggle("active", l.dataset.viewLink===state.view)); attachCancelControls(); app.focus({preventScroll:true}); updateCounts(); updateProjectChrome(); }
function updateCounts(){ $("#riskCount").textContent=state.assumptions.filter(a=>a.risk>=70).length; $("#taskCount").textContent=state.tasks.filter(t=>t.status!=="done").length; }
function updateProjectChrome(){ const name=state.project?.name || "No project loaded", stage=toTitle(state.project?.validation || "database memory"); document.querySelectorAll(".project-switcher strong,.current-project").forEach(el=>{ if(el.classList.contains("current-project")) el.innerHTML=`${esc(name)} <small>${esc(stage)}</small>`; else el.textContent=name; }); document.querySelector(".project-switcher small").textContent=stage; }
function toast(msg) { const el=$("#toast"); el.textContent=msg; el.classList.add("show"); setTimeout(()=>el.classList.remove("show"),2600); }

document.addEventListener("click", e=>{
 const link=e.target.closest("[data-view-link]"); if(link){ e.preventDefault(); location.hash=link.dataset.viewLink; return; }
 const button=e.target.closest("[data-action]"); if(!button) return; const {action,id,key}=button.dataset;
 if(action==="toggle-task"){ const task=state.tasks.find(t=>t.id===id); if(task.status==="done"){mutate(`/api/projects/${state.projectId}/tasks/${id}`,"PATCH",{status:"todo"});}else{state.completionTaskId=id;toast("Add completion evidence before marking this done.");render();} }
 if(action==="select-assumption"){state.selectedAssumption=id; location.hash="assumptions";}
 if(action==="focus-task"){state.view="tasks"; location.hash="tasks"; toast("Your focused task is ready.");}
 if(action==="snooze-rec"){state.recommendation="snoozed";toast("Recommendation snoozed until tomorrow.");render();}
 if(action==="dismiss-rec"){state.recommendation="dismissed";toast("Recommendation dismissed.");render();}
 if(action==="restore-rec"){state.recommendation="active";toast("Recommendation restored.");render();}
 if(action==="confirm-field"){const map={targetCustomer:"target_customer",problem:"problem_statement",solution:"solution_summary",pricing:"pricing_hypothesis"}, project=state.project || state.intakeDraft; if(state.projectId && project && map[key]) mutate(`/api/projects/${state.projectId}`,"PATCH",{[map[key]]:project[key]});}
 if(action==="show-evidence-form"){$("#evidenceForm").classList.remove("hidden");button.classList.add("hidden");}
 if(action==="hide-evidence-form"){$("#evidenceForm").classList.add("hidden");document.querySelector("[data-action=show-evidence-form]").classList.remove("hidden");}
 if(action==="filter-assumptions"){state.assumptionFilter=button.dataset.filter;render();}
 if(action==="show-assumption-form"){state.showAssumptionForm=true;render();}
 if(action==="mark-testing"){mutate(`/api/projects/${state.projectId}/assumptions/${id}`,"PATCH",{status:"testing"});}
 if(action==="link-evidence"){state.linkingEvidenceId=id;render();}
 if(action==="show-experiment-form"){state.showExperimentForm=true;render();}
 if(action==="experiment-menu"){state.experimentMenuId=state.experimentMenuId===id?null:id;render();}
 if(action==="record-result"){state.completingExperimentId=id;state.experimentMenuId=null;render();}
 if(action==="start-experiment"){mutate(`/api/projects/${state.projectId}/experiments/${id}`,"PATCH",{status:"running",started_at:new Date().toISOString()});}
 if(action==="add-task"){state.showTaskForm=true;render();}
 if(action==="cancel-completion"){state.completionTaskId=null;render();}
 if(action==="toggle-project-menu"){$("#projectMenu").classList.toggle("hidden");}
 if(action==="new-project"){state.intakePreview=false;state.intakeDraft=null;location.hash="intake";$("#projectMenu").classList.add("hidden");}
 if(action==="cancel-intake"){state.intakePreview=false;state.intakeDraft=null;state.view=state.project?"today":"today";location.hash=state.project?"today":"today";render();}
 if(action==="cancel-task-form"){state.showTaskForm=false;render();}
 if(action==="cancel-assumption-form"){state.showAssumptionForm=false;render();}
 if(action==="cancel-link-form"){state.linkingEvidenceId=null;render();}
 if(action==="cancel-experiment-form"){state.showExperimentForm=false;render();}
 if(action==="cancel-experiment-result"){state.completingExperimentId=null;render();}
});
document.addEventListener("submit", e=>{
 if(e.target.id==="intakeForm"){e.preventDefault();const f=new FormData(e.target);const payload={name:(f.get("idea")||"New project").slice(0,120),short_description:f.get("idea"),target_customer:f.get("customer"),problem_statement:f.get("problem"),solution_summary:f.get("solution"),pricing_hypothesis:f.get("price"),founder_goal:f.get("goal"),founder_constraints:f.get("progress"),stage:"idea",validation_stage:"idea"};state.intakeDraft=draftProject(payload);state.intakePreview=true;render();request("/api/projects",{method:"POST",body:JSON.stringify(payload)}).then(({project})=>loadMemory(project.id)).catch(error=>toast(error.message));}
 if(e.target.id==="evidenceForm"){e.preventDefault();const f=new FormData(e.target);mutate(`/api/projects/${state.projectId}/evidence`,"POST",{source_type:String(f.get("source")).toLowerCase().replaceAll(" ","_"),source_title:f.get("person"),source_person_name:f.get("person"),summary:f.get("summary"),strength:String(f.get("strength")).toLowerCase(),behavior_vs_opinion:String(f.get("signal")).toLowerCase().replaceAll(" ","_")});}
 if(e.target.id==="completionForm"){e.preventDefault();state.completionTaskId=null;mutate(`/api/projects/${state.projectId}/tasks/${e.target.dataset.id}`,"PATCH",{status:"done"});}
 if(e.target.id==="taskForm"){e.preventDefault();const f=new FormData(e.target);state.showTaskForm=false;mutate(`/api/projects/${state.projectId}/tasks`,"POST",{title:f.get("title"),description:f.get("description"),priority:String(f.get("priority")).toLowerCase(),impact_level:f.get("firstRevenue")?"first_revenue":"medium",estimated_minutes:20});}
 if(e.target.id==="assumptionForm"){e.preventDefault();const f=new FormData(e.target);state.showAssumptionForm=false;mutate(`/api/projects/${state.projectId}/assumptions`,"POST",{statement:f.get("statement"),category:f.get("category"),priority:String(f.get("priority")).toLowerCase(),subcategory:f.get("why"),risk_score:65});}
 if(e.target.id==="linkForm"){e.preventDefault();const f=new FormData(e.target);state.linkingEvidenceId=null;mutate(`/api/projects/${state.projectId}/assumption-evidence`,"POST",{evidence_id:e.target.dataset.id,assumption_id:f.get("assumption"),relationship:String(f.get("relationship")).toLowerCase()});}
 if(e.target.id==="experimentForm"){e.preventDefault();const f=new FormData(e.target);state.showExperimentForm=false;mutate(`/api/projects/${state.projectId}/experiments`,"POST",{title:f.get("title"),hypothesis:f.get("hypothesis"),assumption_id:f.get("assumption"),success_metric:f.get("metric"),expected_duration:f.get("due")});}
 if(e.target.id==="experimentResultForm"){e.preventDefault();const f=new FormData(e.target);state.completingExperimentId=null;mutate(`/api/projects/${state.projectId}/experiments/${e.target.dataset.id}`,"PATCH",{status:"completed",test_design:f.get("result"),completed_at:new Date().toISOString()});}
});
document.addEventListener("focusout", e=>{if(e.target.matches("[data-action=edit-memory]")){const map={name:"name",shortDescription:"short_description",targetCustomer:"target_customer",problem:"problem_statement",solution:"solution_summary",pricing:"pricing_hypothesis",revenueModel:"revenue_model",validation:"validation_stage"};const field=map[e.target.dataset.key];if(field) mutate(`/api/projects/${state.projectId}`,"PATCH",{[field]:e.target.textContent.trim()});}if(e.target.matches("[data-action=edit-assumption-why]")){mutate(`/api/projects/${state.projectId}/assumptions/${e.target.dataset.id}`,"PATCH",{subcategory:e.target.textContent.trim()});}});
window.addEventListener("hashchange",render); request("/api/projects").then(({projects})=>projects[0] ? loadMemory(projects[0].id) : (state.loading=false,render())).catch(error=>{state.loading=false;render();toast(error.message);});
